import = ["~/.config/alacritty/alacritty-theme/themes/Cobalt2.toml"]

[env]
term = "xterm-256color"

[font]
bold = { family = "MesloLGMDZ Nerd Font", style = "Bold" }
bold_italic = { family = "MesloLGMDZ Nerd Font", style = "Bold Italic" }
italic = { family = "MesloLGMDZ Nerd Font", style = "Italic" }
normal = { family = "MesloLGMDZ Nerd Font", style = "Regular" }
size = 16

[window]
